### ISSUE TITLE
Empty Query Creates Server Error

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/susi_server#110]
When I ask nothing https://api.asksusi.com/susi/chat.json?q=
I get an Server Error.
I think, I would expect JSON.

```
HTTP ERROR 500

Problem accessing /susi/chat.json. Reason:

    Server Error

Caused by:

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.charAt(String.java:658)
	at org.loklak.susi.SusiPhrase.normalizeExpression(SusiPhrase.java:94)
	at org.loklak.susi.SusiMind.react(SusiMind.java:480)
	at org.loklak.susi.SusiCognition.<init>(SusiCognition.java:60)
	at org.loklak.api.susi.SusiService.serviceImpl(SusiService.java:110)
	at org.loklak.server.AbstractAPIHandler.process(AbstractAPIHandler.java:152)
	at org.loklak.server.AbstractAPIHandler.doGet(AbstractAPIHandler.java:106)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:419)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.IPAccessHandler.handle(IPAccessHandler.java:219)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)

Powered by Jetty:// 9.3.z-SNAPSHOT 
```

**Comment by Abhi2424shek** [comment]
Can I try something, wont checking for a empty String and returning json stating an error has occurred enough?

**Comment by niccokunzmann** [comment]
I think, JSON is an improvement.

**Comment by DravitLochan** [comment]
@mariobehling We can add a RegEx to check if the user is sending a query composed solely of blank spaces. Please assign it to me so that I can resolve this issue.

**Comment by amitiwary999** [comment]
@DravitLochan What do you mean by query composed solely of blank space? You mean user send nothing but only blank space i.e empty query?

**Comment by DravitLochan** [comment]
exactly!

**Comment by amitiwary999** [comment]
@DravitLochan it can be solved at client side. Like in susi  android app you can't send blank message.

**Comment by DravitLochan** [comment]
You may handle it at client site, but we also need to take care about
api.susi.ai
Hence better we handle it at server only. (Similar to other actions).

**Comment by Orbiter** [comment]
fixed

**Comment by DravitLochan** [comment]
Still giving error. Please check!
