### ISSUE TITLE
Cannot start susi in installation mode

### ISSUE THREAD

**Issue by maxolasersquad** [fossasia/susi_server#1236]
**Actual Behaviour**

When I try to run the installation I get an error.

```sh
$ bin/install.sh
Starting SUSI installation
SUSI installation failed to start. See data/loklak.log for details. Here are the last logs:
WARNING: The following warnings have been detected: WARNING: A HTTP GET method, public org.json.JSONObject ai.susi.server.api.cms.BookmarkSkillService.getDefaultPermissions(ai.susi.server.UserRole), should not consume any entity.
WARNING: A HTTP GET method, public org.json.JSONObject ai.susi.server.api.aaa.UserAccountPermissions.getDefaultPermissions(ai.susi.server.UserRole), should not consume any entity.
WARNING: A HTTP GET method, public org.json.JSONObject ai.susi.server.api.aaa.ShowAdminService.getDefaultPermissions(ai.susi.server.UserRole), should not consume any entity.
WARNING: A HTTP GET method, public org.json.JSONObject ai.susi.server.api.aaa.RemoveUserDevices.getDefaultPermissions(ai.susi.server.UserRole), should not consume any entity.

2019-02-20 14:33:27.964 WARN root  - SKILL PULL THREAD
java.io.IOException: No value for key remote.origin.url found in configuration
        at ai.susi.SkillTransactions.pull(SkillTransactions.java:165)
        at ai.susi.SkillTransactions$1.run(SkillTransactions.java:69)
Error: Could not find or load main class ai.susi.SusiInstallation
```

**Expected Behaviour**

The installation should run

**Steps to reproduce it**

On a brand new installation run `bin/installation.sh`.

**LogCat for the issue**

Where do I find the logs?

**Would you like to work on the issue?**

No

**Comment by norbusan** [comment]
What do you mean with "On a brand new installation"? Did you clone the `susi_server` git repo and tried to run the installation script? I guess you need first to actually *build* the server.

**Comment by maxolasersquad** [comment]
To be honest I don't recall. I have SUSI up and running so I don't see any reason to keep this open.
