### ISSUE TITLE
Conditions for Answers Bug

### ISSUE THREAD

**Issue by AresScorpio** [fossasia/susi_server#1262]
**Actual Behaviour**

If you define a skill with a conditional answer and the variable is empty, susi crashes in 
SusiMind.java#525 trying to access a variable

**Expected Behaviour**

Susi should answer using the then path of the condition

**Steps to reproduce it**
Susi is *
Thank you for calling me $1$>_xyz
Is susi fun?
?$_xyz$=fun:I am $_xyz$.:I don't know

**LogCat for the issue**

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at ai.susi.mind.SusiMind$Reaction.<init>(SusiMind.java:525)
	at ai.susi.mind.SusiAction.execution(SusiAction.java:437)
	at ai.susi.mind.SusiArgument.finding(SusiArgument.java:229)
	at ai.susi.mind.SusiMind.react(SusiMind.java:469)
	at ai.susi.mind.SusiMind.reactMinds(SusiMind.java:514)
	at ai.susi.mind.SusiCognition.<init>(SusiCognition.java:119)
	at ai.susi.server.api.susi.SusiService.serviceImpl(SusiService.java:301)
	at ai.susi.server.api.susi.SusiService.serviceImpl(SusiService.java:76)
	at ai.susi.server.AbstractAPIHandler.process(AbstractAPIHandler.java:138)
	at ai.susi.server.AbstractAPIHandler.doGet(AbstractAPIHandler.java:78)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1780)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:308)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:262)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1767)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:513)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.IPAccessHandler.handle(IPAccessHandler.java:221)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at ai.susi.tools.MultipartConfigInjectionHandler.handle(MultipartConfigInjectionHandler.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:539)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
** Screenshot **

![grafik](https://user-images.githubusercontent.com/3578989/58483340-69992b00-8160-11e9-9f93-fb72e11b9384.png)

**Would you like to work on the issue?**
Not sure if i can fix this since i'm new to the whole susi stuff

**Comment by Orbiter** [comment]
This is not a bug because the skill has a missing empty line between the intents.
However, a fix for the behaviour (IndexOutOfBoundsException) was required.
So the behavior of susi is correct because the skill is incorrect, only the way this was achieved was wrong.
