### ISSUE TITLE
Geocoding and SusiTutorialTest are  failing

### ISSUE THREAD

**Issue by saurabhjn76** [fossasia/susi_server#236]
**Actual Behaviour**

Currently, 2 out of 15 tests are failing.

- SusiTutorialTest

- Geocoding Test

**Expected Behaviour**

All test must pass.

**LogCat for the issue**

- **SusiTutorial Test** - 
    ** fail for: Ciao
    ** expected: Hello
    ** returned: Heisst das jetzt Hallo oder Tschuess?

   ** fail for: For one dollar I can buy a beer
   ** expected: Yeah, I believe one dollar is a god price for a beer
   ** returned: And another?

- Geocoding Test
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at ai.susi.geo.GeocodingTest.testGeocoding(GeocodingTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

```

Provide logs for the crash here

**Screenshots of the issue**
![image](https://cloud.githubusercontent.com/assets/9781788/26765007/0ced5002-4990-11e7-9ece-7afd07f66e88.png)

**Would you like to work on the issue?**

Yes

**Comment by saurabhjn76** [comment]
For SusiTutorial Test 
- `Ciao `is giving `Heisst das jetzt Hallo oder Tschuess?` as written in [GermanStandaloneaiml2susi](https://github.com/fossasia/susi_skill_data/blob/master/models/general/smalltalk/de/German-Standalone-aiml2susi.txt).
Also for 
- `For one dollar I can buy a beer` is giving `And another?` as written in [English-Standalone-aiml2susi.txt](https://github.com/fossasia/susi_skill_data/blob/master/models/general/smalltalk/en/English-Standalone-aiml2susi.txt)
I couldn't figure out why this is happening.
 @Orbiter  please guide.

**Comment by Orbiter** [comment]
These test failures are often cause by alternate skills which match also with the given query and have a different outcomes. To fix this, you must find the actual skills which produce the unexpected outcome and think about if they can be replaced or if the test is applicable in that way at all.
Yes it's a beast.

**Comment by saurabhjn76** [comment]
@Orbiter :+1: , I think in this case test can be modified.

**Comment by saurabhjn76** [comment]
fixed
