### ISSUE TITLE
Login API is not working

### ISSUE THREAD

**Issue by betterclever** [fossasia/susi_server#302]
**Actual Behaviour**

Login API endpoint is not working. It is giving 500 error, even when supplied with correct username and password.

**Expected Behaviour**

This API is crucial and must be working.

**Steps to reproduce it**

Send a GET request to http://api.susi.ai/aaa/login.json?type=access-token&login=LOGIN_EMAIL&password=LOGIN_PASSWORD

or try logging in in any Susi Client

Server with replies with error 500

**LogCat for the issue**
```
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
        <title>Error 500 Server Error</title>
    </head>
    <body>
        <h2>HTTP ERROR 500</h2>
        <p>Problem accessing /aaa/login.json. Reason:

            <pre>    Server Error</pre>
        </p>
        <h3>Caused by:</h3>
        <pre>java.lang.NullPointerException
	at ai.susi.server.api.aaa.LoginService.checkInvalidLogins(LoginService.java:365)
	at ai.susi.server.api.aaa.LoginService.serviceImpl(LoginService.java:131)
	at ai.susi.server.AbstractAPIHandler.process(AbstractAPIHandler.java:120)
	at ai.susi.server.AbstractAPIHandler.doGet(AbstractAPIHandler.java:73)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.IPAccessHandler.handle(IPAccessHandler.java:221)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
</pre>
        <hr>
        <a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.z-SNAPSHOT</a>
        <hr/>
    </body>
</html>
```
**Screenshots of the issue**

![image](https://user-images.githubusercontent.com/16309034/27267885-4705c80c-54c9-11e7-8e8d-26b75c19f225.png)

**Would you like to work on the issue?**

Anyone is free to take this up.
@dynamitechetan @saurabhjn76 You may solve it.

**Comment by DravitLochan** [comment]
I'd like to work  on this.

**Comment by betterclever** [comment]
Fixed in commit https://github.com/fossasia/susi_server/commit/320cc24c82359f4530465c34b3b5d0b525f67de4
