### ISSUE TITLE
SUSI Server isn't responding

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_server#834]
**Actual Behaviour**
SUSI Server isn't responding

**Expected Behaviour**
It should work normally.

**Steps to reproduce it**
Hit chat API of SUSI.

**LogCat for the issue**
```
HTTP ERROR 500
Problem accessing /susi/chat.json. Reason:

    Server Error
Caused by:
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1378)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at ai.susi.tools.TimeoutMatcher.matches(TimeoutMatcher.java:59)
	at ai.susi.mind.SusiIntent.matcher(SusiIntent.java:541)
	at ai.susi.mind.SusiMind.creativity(SusiMind.java:335)
	at ai.susi.mind.SusiMind.react(SusiMind.java:380)
	at ai.susi.mind.SusiMind.reactMinds(SusiMind.java:413)
	at ai.susi.mind.SusiCognition.<init>(SusiCognition.java:80)
	at ai.susi.server.api.susi.SusiService.serviceImpl(SusiService.java:158)
	at ai.susi.server.AbstractAPIHandler.process(AbstractAPIHandler.java:138)
	at ai.susi.server.AbstractAPIHandler.doGet(AbstractAPIHandler.java:78)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:448)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.IPAccessHandler.handle(IPAccessHandler.java:221)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at ai.susi.tools.MultipartConfigInjectionHandler.handle(MultipartConfigInjectionHandler.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:539)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:333)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
Powered by Jetty:// 9.3.z-SNAPSHOT

```

**Would you like to work on the issue?**
Yes

**Comment by sudheesh001** [comment]
Ah, Out of memory problems,. @Orbiter Can we tweak the server to have a higher heap size? `-Xmx`?

**Comment by mariobehling** [comment]
@sudheesh001 The same issue appears on Heroku. What options exist to make it work also on Heroku again? https://susi-server.herokuapp.com/susi/chat.json?timezoneOffset=-120&q=hi

**Comment by akshatnitd** [comment]
This has been fixed. Closing the issue.
